apiVersion: apps/v1
kind: Deployment
metadata:
  name: btcwallet-ui
  labels:
    app: btcwallet-ui
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: btcwallet-ui
  template:
    metadata:
      labels:
        app: btcwallet-ui
    spec:
      containers:
      - name: btcwallet-ui-container
        image: apptrustinfra.jfrog.io/btcwallet-prod-docker-local/btcwallet-ui:36
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: apptrustinfra
