apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-translate
  labels:
    app: ai-translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-translate
  template:
    metadata:
      labels:
        app: ai-translate
    spec:
      containers:
      - name: ai-translate-container
        image: evidencetrial.jfrog.io/commons-dev-docker-local/ai-translate:23 
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: evidencetrial
