apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteofday
  labels:
    app: quoteofday
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: quoteofday
  template:
    metadata:
      labels:
        app: quoteofday
    spec:
      containers:
      - name: quoteofday-container
        image: apptrustswampup.jfrog.io/quotopia-prod-docker/quoteofday:236
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: apptrustswampup
