apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotopia-ui
  labels:
    app: quotopia-ui
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: quotopia-ui
  template:
    metadata:
      labels:
        app: quotopia-ui
    spec:
      containers:
      - name: quotopia-ui-container
        image: evidencetrial.jfrog.io/commons-dev-docker-local/quotopia-ui:2 
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: evidencetrial
